image: maven:3.5-jdk-8-alpine
before_script:
  - echo '<settings
          xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
          https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>viaa-snapshots</id>
              <username>${env.NEXUS_SNAPSHOTS_USERNAME}</username>
              <password>${env.NEXUS_SNAPSHOTS_PASSWORD}</password>
            </server>
            <server>
              <id>viaa-releases</id>
              <username>${env.NEXUS_RELEASES_USERNAME}</username>
              <password>${env.NEXUS_RELEASES_PASSWORD}</password>
            </server>
          </servers>
          <proxies>
              <proxy>
                  <id>viaa-http</id>
                  <active>true</active>
                  <protocol>http</protocol>
                  <host>${env.PROXY_HOST}</host>
                  <port>80</port>
                  <nonProxyHosts>*.viaa.be</nonProxyHosts>
              </proxy>
              <proxy>
                  <id>viaa-https</id>
                  <active>true</active>
                  <protocol>https</protocol>
                  <host>${env.PROXY_HOST}</host>
                  <port>80</port>
                  <nonProxyHosts>*.viaa.be</nonProxyHosts>
              </proxy>
          </proxies>
      </settings>' > /root/.m2/settings-docker.xml

#cache:
#  paths:
#    - $HOME/.m2/repository

build:
  stage: build
  script: mvn package
test:
  stage: test
  script: mvn test
deploy:
  stage: deploy
  script: mvn deploy