image: maven:3.5-jdk-8-alpine
before_script:
  - echo '<settings
          xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
          https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
            <server>
              <id>viaa-snapshots</id>
              <username>$NEXUS_SNAPSHOTS_USERNAME</username>
              <password>$NEXUS_SNAPSHOTS_PASSWORD</password>
            </server>
            <server>
              <id>viaa-releases</id>
              <username>$NEXUS_RELEASES_USERNAME</username>
              <password>$NEXUS_RELEASES_PASSWORD</password>
            </server>
          </servers>
          <proxies>
              <proxy>
                  <active>true</active>
                  <protocol>http</protocol>
                  <host>$PROXY_HOST</host>
                  <port>$PROXY_PORT</port>
                  <nonProxyHosts>*.viaa.be</nonProxyHosts>
                  <active>true</active>
              </proxy>
              <proxy>
                  <active>true</active>
                  <protocol>https</protocol>
                  <host>$PROXY_HOST</host>
                  <port>$PROXY_PORT</port>
                  <nonProxyHosts>*.viaa.be</nonProxyHosts>
                  <active>true</active>
              </proxy>
          </proxies>
      </settings>' > $HOME/.m2/settings.xml

cache:
  paths:
    - $HOME/.m2/repository

build:
  stage: build
  script: mvn package
test:
  stage: test
  script: mvn test
deploy:
  stage: deploy
  script: mvn deploy